---
# the comments are too noisy to be useful
comment: false

coverage:
  precision:    1
  round: nearest
  status:
    project:
      default:
        # dropping slightly is ok
        threshold: 1.0
