---
package:
  name: "stellargraph"
  version: "1.1.0"

source:
  path: .

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true # [py<36]

requirements:
  host:
    # requirements to build stellargraph
    - python
  run:
    # requirements to run stellargraph
    - gensim >=3.4.0
    - matplotlib >=2.2
    - networkx >=2.2
    - numpy >=1.14
    - pandas >=0.24
    - python >=3.6
    - scikit-learn >=0.20
    - scipy >=1.1.0
    - tensorflow >=2.1.0
    - ipython
    - ipykernel

test:
  imports:
    # this section tests imports of stellargraph and will need updating as our api evolves
    - stellargraph
    - stellargraph.connector
    - stellargraph.connector.neo4j
    - stellargraph.core
    - stellargraph.data
    - stellargraph.datasets
    - stellargraph.interpretability
    - stellargraph.interpretability.saliency_maps
    - stellargraph.layer
    - stellargraph.mapper
    - stellargraph.utils
  requires:
    - pytest
    - pytest-benchmark >= 3.1
  source_files:
    # we only bundle and run a subset of tests as a 'smoke test'
    - tests/__init__.py
    - tests/test_utils
    - tests/core
    - tests/layer
  commands:
    - py.test -ra -p no:cacheprovider --benchmark-disable --color=yes tests/
about:
  home: "https://github.com/stellargraph/stellargraph"
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: "Python library for machine learning on graphs"
  doc_url: https://stellargraph.readthedocs.io/
  dev_url: https://github.com/stellargraph/stellargraph
