---
# configure the parameters replaced in jupyter notebooks when running on CI with papermill
# common parameters used in several notebooks:
epochs: 2
batch_size: 5
# short random walks
walk_length: 5
context_window_size: 5
# minimal ensembles:
n_estimators: 2
n_predictions: 2
# reduce graph size for movielens-recommender.ipynb and calibration-pubmed-link-prediction.ipynb:
train_size: 0.005
test_size: 0.01
val_size: 0.01
# minimal metapaths for demos/embeddings/stellargraph-metapath2vec.ipynb:
metapaths: [["group", "group"], ["group", "user", "user", "group"]]
# tiny embeddings for demos/link-prediction/knowledge-graphs/complex.ipynb
embedding_dimension: 5
# training of fewer models for demos/graph-classification/supervised-graph-classification.ipynb
folds: 2
num_restarts: 2
# a small number of random walks for demos/embeddings/stellargraph-keras-node2vec.ipynb
# and demos/node-classification/node2vec/stellargraph-keras-node2vec-node-classification.ipynb
walk_number: 2
